### ISSUE TITLE
Issue when running.

### ISSUE THREAD

**Issue by OneLegSkank** [piscripts/pijarr#3]
`Err:3 http://apt.sonarr.tv master InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EBFF6B99D9B78493
Reading package lists... Done
W: GPG error: http://apt.sonarr.tv master InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EBFF6B99D9B78493
E: The repository 'http://apt.sonarr.tv master InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

**Comment by piscripts** [comment]
Script has been updated 6 Aug 2021 and will now grab latest releases. Link to Sonarr release has now changed. I've tested and did not have the issue you experienced above. Give is another try.
